development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: sinatra_postgres_dev
  username: postgres
  password: ankit1234


production:
  adapter: postgresql            
  host: < host >                          # VM IP
  port: < port >                          # VM Port 
  database: < database name >             # Database Name
  username: < user_name >                 # User Name
  password: '< password >'                # password
